### ISSUE TITLE
Regarding the depthmap_undistorted

### ISSUE THREAD

**Issue by wtyuan96** [dimitrisPs/scared_toolkit#4]
Thanks for your great work!

I am confused about the calculation of `depthmap_undistorted`.
In your [code](https://github.com/dimitrisPs/scared_toolkit/blob/2c76e2874b5d5bc9dd3204d4dff03cdd9ae29e63/scripts/generate_sequence_dataset.py#L87C55-L87C55), you project `gt_ptcloud` to `img3d` with `calib['K1']` and `calib['D1']`, and further use the function `img3d_to_depthmap` to get `depthmap_undistorted`. Why use `calib['D1']`? Shouldn't it be projected with zero distortion coefficients to get the **undistorted depth map**?

Thanks in advance!

**Comment by dimitrisPs** [comment]
Hello, 

Thank you for reaching out and your nice comments about the work. Also, thank you for taking the time to read the script and pointing this out.

Although I do not remember details from when I wrote the script, it seems you are right, **this looks like an error to me as well.** 

If by any chance you did test the output you can confirm there is an error, I am more than happy to push a fix, or better yet, accept a pull request from you.
 
The way I would test the output of the script would be to generate both undistorted and distorted depthmaps(.png) and their corresponding RGB images. Then I would check if depthmaps align with the corresponding RGB images. Alternatively, I would check if the distorted depthmaps generated by the script align with the 3rd channel of the corresponding .tiff files provided as a part of the original dataset. 

If you are not able to confirm the error, I will run the test myself. However, due to very low time bandwidth on my side, I am not sure when I will be able to have a look.

**Comment by wtyuan96** [comment]
Thank you for your response. The verification method you provided is very reasonable. 
However, based on my testing, the distortion parameters are very small, resulting in minimal differences between distorted and undistorted RGB images as well as depth maps. The discrepancies in projecting 3D coordinates to 2D coordinates are also very slight. Therefore, purely judging from the results is not sufficient for validation.

From a theoretical standpoint, it is indeed inappropriate to use distortion parameters when obtaining an undistorted depth map.

**Comment by dimitrisPs** [comment]
Hello, 

I'm sorry for the late response, I did the experiments myself and came to the same conclusion as you.

On the positive side, the fact that there wasn't a lot of distortion is a good thing because the error you pointed out does not seem to affect the generated data much. 

Nevertheless, I am going to push a fix soon and once again thank you for reporting this.

**Comment by wtyuan96** [comment]
The code also contains another very minor bug. The distortion parameter order for datasets 4/5/6/7 is different from datasets 1/2/3, so it is necessary to add the following lines of code [at this position ](https://github.com/dimitrisPs/scared_toolkit/blob/8ee8e499aef70c5f590173e2f2b0515c55e755a3/scaredtk/calibrator.py#L63)to distinguish between them.

```python
if str(path).split('/')[-3] in ['dataset_4', 'dataset_5', 'dataset_6', 'dataset_7']:
    self.calib['D1'] = self.calib['D1'][:, [0, 1, 3, 4, 2]]
    self.calib['D2'] = self.calib['D2'][:, [0, 1, 3, 4, 2]]
```
Although, as discussed above, the impact of this small bug is minimal.

Thank you very much for your response and patience. I will close this issue.
